### ISSUE TITLE
UI in Mobile Screens

### ISSUE THREAD

**Issue by SubhamKarmakar24** [SubhamKarmakar24/snake#17]
Should support all types of screen sizes.
Use media query to implement responsiveness.
Already using [Materialize CSS](https://materializecss.com/), so using this to make responsive website would help

**Comment by ampsteric** [comment]
hi , please assign me this issue @SubhamKarmakar24

**Comment by SubhamKarmakar24** [comment]
> 
> 
> hi , please assign me this issue @SubhamKarmakar24

Sure, feel free to contribute

**Comment by ampsteric** [comment]
#27

**Comment by ampsteric** [comment]
I have made a PR resolving this issue , please check #27 .

**Comment by SubhamKarmakar24** [comment]
> 
> 
> I have made a PR resolving this issue , please check #27 .

Sure, I will verify the PR and merge it/add hacktoberfest-accepted label by end of today
