### ISSUE TITLE
Update README.md file to make it more professional

### ISSUE THREAD

**Issue by SubhamKarmakar24** [SubhamKarmakar24/snake#24]
**Is your feature request related to a problem? Please describe.**
The READ ME isn't great.

**Describe the solution you'd like**
Update the README.md file with clear description of the project, screenshots and gifs of the website, what it does, web techs used, how to set up the development environment, how to run it and its link, update CONTRIBUTING.md file and referring it in Read me, and the licence details.

**Describe alternatives you've considered**
None

**Additional context**
Any small changes or deleting and re-adding lines and bad read me formatting PRs will be rejected.
Try to follow a good read me pattern. You can take hint from [this](https://github.com/SubhamKarmakar24/snapshot#snapshot).

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Please assign me this issue!

Yes, you may work on it @aniket-24

**Comment by SamikshaSankar** [comment]
Please assign me @SubhamKarmakar24

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Please assign me @SubhamKarmakar24

Sure, feel free to contribute

**Comment by SamikshaSankar** [comment]
@SubhamKarmakar24 Please review my PR

**Comment by SubhamKarmakar24** [comment]
> 
> 
> @SubhamKarmakar24 Please review my PR

@SamikshaSankar I have requested a few changes in the PR.
Please make the necessary changes. I will approve it after you complete them.
Cheers :)

**Comment by SamikshaSankar** [comment]
Where I can find what changes you want?

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Where I can find what changes you have?

It is present in the Pull Request that you made. The link is
https://github.com/SubhamKarmakar24/snake/pull/36
Scroll down to see all the changes requested

**Comment by SamikshaSankar** [comment]
@SubhamKarmakar24 which framework and stack u used ?

**Comment by SamikshaSankar** [comment]
@SubhamKarmakar24 I have made new changes but due to merged repo it is not shown(I have update readme file in that adding web tech and license)

**Comment by SubhamKarmakar24** [comment]
> 
> 
> @SubhamKarmakar24 I have made new changes but due to merged repo it is not shown(I have update readme file in that adding web tech and license)

You can make another PR for the changes.
