### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by SubhamKarmakar24** [SubhamKarmakar24/snake#3]
For different difficulty levels and for different mazes, the code is spread out into separate .html files. All these can be merged into one file and the different levels and mazes can be conditionally rendered depending on user choices by fetching the .js codes from separate files

**Comment by luthrap** [comment]
I would like to pick this up.

**Comment by SubhamKarmakar24** [comment]
> 
> 
> I would like to pick this up.

Yes, sure

**Comment by r4pt0s** [comment]
Hi,
If you still need help for the code refactoring, let me know. 
I would be happy to help out.

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Hi,
> If you still need help for the code refactoring, let me know.
> I would be happy to help out.

Feel free to contribute

**Comment by r4pt0s** [comment]
I just don't want to work against @luthrap.
Shall we split up the work or are you already on all of it?

**Comment by SubhamKarmakar24** [comment]
> 
> 
> I just don't want to work against @luthrap.
> Shall we split up the work or are you already on all of it?

You both can split up the work. @luthrap @r4pt0s 
You can comment down below the approach you all will be taking and divide the task among yourself

**Comment by luthrap** [comment]
I have already made some changes and should be done by tomorrow as i am not free today. Should we still split.

**Comment by SubhamKarmakar24** [comment]
> I have already made some changes and should be done by tomorrow as i am not free today. Should we still split.

If you are able to complete by tomorrow, then there is no more need to split. But if you need any help, then you can discuss with @r4pt0s and split the work.

**Comment by r4pt0s** [comment]
Totally.
If you don't mind @luthrap I can read through the codebase and add some things to it if find something else to do.
Or even better, after @SubhamKarmakar24 looked into it, I can jump in again if there is something else left to do.

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Totally.
> If you don't mind @luthrap I can read through the codebase and add some things to it if find something else to do.
> Or even better, after @SubhamKarmakar24 looked into it, I can jump in again if there is something else left to do.

Yes. You can do them. Also, there might be some new issues that might have missed my eyes. If you can find them out, you can work on them as well by raising an issue.

**Comment by SubhamKarmakar24** [comment]
Issue fixed

**Comment by luthrap** [comment]
There has been a recent change about what contribution will be considered towards hacktoberfest.
https://hacktoberfest.digitalocean.com/hacktoberfest-update. I believe the repo is marked as hacktoberfest, however could you please confirm.
