### ISSUE TITLE
Snake dies when directed in opposite direction of movement

### ISSUE THREAD

**Issue by aanchal-fatwani** [SubhamKarmakar24/snake#32]
**Describe the bug**
While trying to move the snake in the opposite direction of its movement, the snake immediately dies.

**Expected behavior**
Acc. to the traditional rules of the snake game, the snake should not honour the request to move backwards, or in opposite direction of movement.

**Comment by aanchal-fatwani** [comment]
Hi @SubhamKarmakar24 , I would like to work on the resolution of this issue. Please assign the same.

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Hi @SubhamKarmakar24 , I would like to work on the resolution of this issue. Please assign the same.

Sure, feel free to contribute
