### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by SubhamKarmakar24** [SubhamKarmakar24/snake#4]
Preferably some Material UI library to make the game look better

**Comment by BLNDLYBLV** [comment]
I don't know material UI but I can build good UI with CSS , So please consider appointing this issue to me

**Comment by SubhamKarmakar24** [comment]
> 
> 
> I don't know material UI but I can build good UI with CSS , So please consider appointing this issue to me

Sure. Feel free to contribute

**Comment by SubhamKarmakar24** [comment]
@BLNDLYBLV if you are working on this, you can take up issue #6 simultaneously if you want

**Comment by Capt-Titanium** [comment]
@SubhamKarmakar24 can you assign me issue #6 . I can also use materialise-css if you want that.
